# Generated by Django 5.2.6 on 2025-09-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
