# Generated by Django 5.2.6 on 2025-09-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO', '0002_alter_task_options_task_order_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
