# Generated by Django 5.2.6 on 2025-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO', '0003_alter_task_options_remove_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
        ),
    ]
